AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 35

Metrics/BlockLength:
  Max: 70
  Enabled: false
  # not released yet but will be soon, then we can enable this check again
  # ExcludedMethods: ['describe', 'it']

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: hash_rockets

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: true
  EnforcedStyle: no_empty_lines

Layout/EmptyLinesAroundModuleBody:
  Enabled: true
  EnforcedStyle: no_empty_lines

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/DotPosition:
  Enabled: true
  EnforcedStyle: trailing

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
  SupportedStyles:
    - aligned
    - indented

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Lambda:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Performance/Casecmp:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/FirstParameterIndentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
