files:
  include: '**/*.s+(a|c)ss'
options:
  merge-default-rules: false
rules:
  border-zero:
    - 1
    - convention: none
  class-name-format: 0
  clean-import-paths: 0
  empty-line-between-blocks: 1
  extends-before-declarations: 1
  extends-before-mixins: 1
  final-newline: 1
  function-name-format:
    - 1
    - convention: hyphenatedlowercase
  hex-length: 0
  hex-notation:
    - 1
    - style: lowercase
  id-name-format: 0
  indentation: 1
  leading-zero:
    - 1
    - include: true
  mixin-name-format:
    - 1
    - convention: hyphenatedlowercase
  mixins-before-declarations: 1
  nesting-depth: 0
  no-color-keywords: 0
  no-color-literals: 0
  no-css-comments: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-ids: 1
  no-important: 1
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties: 1
  no-qualifying-elements: 1
  no-trailing-zero: 1
  no-transition-all: 1
  no-vendor-prefixes: 1
  placeholder-name-format: 0
  property-sort-order: 0
  quotes:
    - 1
    - style: single
  shorthand-values: 1
  single-line-per-selector: 1
  space-after-colon: 1
  space-after-comma: 1
  space-before-brace: 1
  space-before-colon: 1
  space-between-parens:
    - 1
    - include: false
  trailing-semicolon: 1
  url-quotes: 1
  variable-name-format:
    - 1
    - convention: hyphenatedlowercase
  zero-unit: 1